version: '3.8'

services:
    database:
        image: postgres:14
        restart: always
        env_file:
            - .env
        ports:
            - ${POSTGRES_PORT}:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
    api:
        build:
            context: .
        image: rocket-template
        restart: always
        env_file:
            - .env
        ports:
            - 5556:${PORT}
        links:
            - "database:localhost"
        depends_on:
            - database
volumes:
    pgdata:
