version: '3.8'

services:
    database:
        image: postgres:14
        restart: always
        env_file:
            - .env
        ports:
            - ${POSTGRES_PORT}:5432
volumes:
    pgdata:
