name: Rocket CI

on:
    push:
    pull_request:

env:
    PROJECT_NAME: rocket-template
    CARGO_TERM_COLOR: always

jobs:
    build:
        name: Cargo build - latest
        runs-on: ubuntu-latest
        strategy:
            matrix:
                toolchain:
                    - stable
                    - nightly
        steps:
            - uses: actions/checkout@v2
            - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix. toolchain }}
            - run: cargo check --verbose
            - run: cargo build --verbose
    test:
        name: Cargo test - latest
        needs: build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                toolchain:
                    - stable
                    - nightly
        steps:
            - uses: actions/checkout@v2
            - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix. toolchain }}
            - run: cargo test --verbose
    docker_build:
        name: Docker build - latest
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: docker build --build-arg project=${{ env.PROJECT_NAME }} -t ${{ env.PROJECT_NAME }}:latest .
